2020-01-29 01:34:47.268 DEBUG main - <module>: This message should go to the log file
2020-01-29 01:50:30.736 DEBUG main - <module>: Iniciando Servicio
2020-01-29 01:51:30.115 DEBUG main - <module>: Iniciando Servicio
2020-01-29 01:51:30.119 DEBUG main - main: Conecrado al broker
2020-01-29 02:46:14.899 DEBUG main - <module>: Iniciando Servicio
2020-01-29 02:46:15.020 DEBUG main - main: Conectano al broker
2020-01-29 02:48:52.612 DEBUG main - <module>: Iniciando Servicio
2020-01-29 02:48:52.630 INFO _internal - _log:  * Running on http://localhost:5000/ (Press CTRL+C to quit)
2020-01-29 02:50:09.497 INFO _internal - _log: 127.0.0.1 - - [29/Jan/2020 02:50:09] "GET / HTTP/1.1" 200 -
2020-01-29 02:50:10.239 INFO _internal - _log: 127.0.0.1 - - [29/Jan/2020 02:50:10] "GET /favicon.ico HTTP/1.1" 404 -
2020-01-29 02:51:36.132 DEBUG main - main: Conectano al broker
2020-01-29 03:35:36.243 DEBUG main - <module>: Iniciando Servicio
2020-01-29 03:35:36.253 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-01-29 03:35:45.194 INFO _internal - _log: 127.0.0.1 - - [29/Jan/2020 03:35:45] "GET / HTTP/1.1" 200 -
2020-01-29 03:35:45.704 INFO _internal - _log: 127.0.0.1 - - [29/Jan/2020 03:35:45] "GET /favicon.ico HTTP/1.1" 404 -
2020-01-29 04:19:07.137 DEBUG main - main: Conectano al broker
2020-02-01 02:49:47.931 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:49:48.004 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:52:42.314 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:52:42.337 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:53:42.681 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:53:42.712 DEBUG main - main: Conectano al broker
2020-02-01 02:53:42.720 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:55:23.916 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:55:23.940 DEBUG main - main: Conectano al broker
2020-02-01 02:55:23.943 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:56:14.080 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:56:14.090 DEBUG main - main: Conectando al broker
2020-02-01 02:56:14.091 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 02:57:12.109 DEBUG main - <module>: Iniciando Servicio
2020-02-01 02:57:12.128 DEBUG main - main: Conectando al broker
2020-02-01 02:57:12.131 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:04:25.478 DEBUG main - <module>: Iniciando Servicio
2020-02-01 03:04:25.501 DEBUG main - main: Conectando al broker
2020-02-01 03:04:25.504 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:39.178 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:39.598 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:41.523 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:41.798 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:42.073 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:05:42.442 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:06:27.368 DEBUG main - <module>: Iniciando Servicio
2020-02-01 03:06:27.389 DEBUG main - main: Conectando al broker
2020-02-01 03:06:42.453 DEBUG main - <module>: Iniciando Servicio
2020-02-01 03:06:42.465 DEBUG main - main: Conectando al broker
2020-02-01 03:06:42.491 INFO _internal - _log:  * Running on http://localhost:1313/ (Press CTRL+C to quit)
2020-02-01 03:06:52.847 DEBUG main - on_message: Incoming message!
2020-02-01 06:05:56.869 DEBUG main - <module>: Iniciando Servicio
2020-02-01 06:06:38.406 DEBUG main - <module>: Iniciando Servicio
2020-02-01 13:56:50.978 DEBUG main - <module>: Iniciando Servicio
2020-02-01 13:58:39.210 DEBUG main - <module>: Iniciando Servicio
2020-02-01 13:59:23.517 DEBUG main - <module>: Iniciando Servicio
2020-02-01 13:59:36.017 DEBUG main - <module>: Iniciando Servicio
2020-02-01 20:56:26.807 DEBUG main - <module>: Iniciando Servicio
2020-02-01 20:57:36.041 DEBUG main - <module>: Iniciando Servicio
2020-02-01 20:59:54.401 DEBUG main - <module>: Iniciando Servicio
2020-02-01 21:00:46.200 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:42:45.556 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:43:02.284 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:43:24.727 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:44:35.875 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:52:28.094 DEBUG main - <module>: Iniciando Servicio
2020-02-01 22:53:19.821 DEBUG main - <module>: Iniciando Servicio
2020-02-01 23:58:24.239 DEBUG main - <module>: Iniciando Servicio
2020-02-01 23:59:11.047 DEBUG main - <module>: Iniciando Servicio
2020-02-01 23:59:25.720 DEBUG main - <module>: Iniciando Servicio
2020-02-02 00:39:22.383 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:14:55.626 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:17:14.261 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:17:47.126 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:18:32.720 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:19:23.765 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:19:45.648 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:21:58.573 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:22:31.729 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:22:51.053 DEBUG main - <module>: Iniciando Servicio
2020-02-02 05:35:11.734 DEBUG main - <module>: Iniciando Servicio
2020-02-02 06:39:23.133 DEBUG main - <module>: Iniciando Servicio
2020-02-02 06:40:00.165 DEBUG main - <module>: Iniciando Servicio
2020-02-02 06:40:00.259 DEBUG main - main: Conectando al broker
2020-02-02 06:40:00.266 INFO _internal - _log:  * Running on http://localhost:8080/ (Press CTRL+C to quit)
2020-02-02 06:44:57.128 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 06:44:57.323 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 06:44:57] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 17:22:27.263 DEBUG main - <module>: Iniciando Servicio
2020-02-02 17:22:27.461 DEBUG main - main: Conectando al broker
2020-02-02 17:22:27.478 INFO _internal - _log:  * Running on http://localhost:8080/ (Press CTRL+C to quit)
2020-02-02 17:24:08.379 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 17:24:08.435 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 17:24:08] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:35:25.523 DEBUG main - <module>: Iniciando Servicio
2020-02-02 22:35:25.712 DEBUG main - main: Conectando al broker
2020-02-02 22:35:25.724 INFO _internal - _log:  * Running on http://localhost:8080/ (Press CTRL+C to quit)
2020-02-02 22:35:37.799 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:35:37.873 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:35:37] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:36:33.920 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:36:33.923 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:36:33] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:37:11.414 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:37:11.419 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:37:11] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:37:23.927 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:37:23.936 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:37:23] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:38:41.310 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:38:41.315 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:38:41] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:43:15.713 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:43:15.721 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:43:15] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:44:25.134 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:44:25.140 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:44:25] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:45:18.067 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:45:18.072 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:45:18] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:52:47.926 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:52:47.929 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:52:47] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-02 22:52:54.934 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-02 22:52:54.942 INFO _internal - _log: 127.0.0.1 - - [02/Feb/2020 22:52:54] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:14:47.694 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:14:47.706 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:14:47] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:15:01.763 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:15:01.767 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:15:01] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:20:31.346 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:20:31.353 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:20:31] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:20:38.005 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:20:38.012 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:20:38] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 00:20:55.850 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 00:20:55.863 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 00:20:55] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:03:31.817 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:03:31.820 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:03:31] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:05:41.804 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:05:41.810 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:05:41] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:17:26.572 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:17:26.575 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:17:26] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:17:39.385 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:17:39.390 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:17:39] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:20:46.265 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:20:46.268 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:20:46] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:21:00.000 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:21:00.044 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:21:00] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:21:11.190 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:21:11.193 INFO _internal - _log: 127.0.0.1 - - [03/Feb/2020 02:21:11] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:30:41.897 DEBUG main - <module>: Iniciando Servicio
2020-02-03 02:30:42.084 DEBUG main - main: Conectando al broker
2020-02-03 02:30:42.394 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-03 02:30:51.415 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:30:51.441 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:30:51] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:31:55.199 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:31:55.205 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:31:55] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:32:06.597 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:32:06.602 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:32:06] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:32:34.342 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:32:34.358 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:32:34] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:33:39.225 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:33:39.232 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:33:39] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:33:53.545 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:33:53.554 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:33:53] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:34:10.592 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:34:10.602 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:34:10] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 02:46:36.832 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 02:46:36.835 INFO _internal - _log: 192.168.0.22 - - [03/Feb/2020 02:46:36] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 16:58:19.319 DEBUG main - <module>: Iniciando Servicio
2020-02-03 16:58:19.591 DEBUG main - main: Conectando al broker
2020-02-03 16:59:26.132 DEBUG main - <module>: Iniciando Servicio
2020-02-03 16:59:26.249 DEBUG main - main: Conectando al broker
2020-02-03 16:59:26.513 INFO _internal - _log:  * Running on http://192.168.0.9:8080/ (Press CTRL+C to quit)
2020-02-03 17:01:02.306 ERROR _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:01:02] code 400, message Bad request syntax ('\x16\x03\x01\x00\x94\x01\x00\x00\x90\x03\x03\x11~\x0e\x03\x98$$Õ\x9e¼\x12\x93\x1d«·ñ\x86+ÅnSv©Æ\x80¬ãð\x16ÃÏ[\x00\x00\x1cÀ+À,Ì©À/À0Ì¨À\tÀ')
2020-02-03 17:01:02.313 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:01:02] "   ~$$Õ¼«·ñ+ÅnSv©Æ¬ãðÃÏ[  À+À,Ì©À/À0Ì¨À	À" HTTPStatus.BAD_REQUEST -
2020-02-03 17:01:39.204 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:01:39] "POST /api/device/switch HTTP/1.1" 400 -
2020-02-03 17:02:45.835 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 17:02:45.866 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:02:45] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 17:02:58.600 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 17:02:58.616 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:02:58] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 17:03:10.130 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 17:03:10.149 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:03:10] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-03 17:05:01.919 ERROR app - log_exception: Exception on /api/device/switch [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-03 17:05:01.944 INFO _internal - _log: 192.168.0.3 - - [03/Feb/2020 17:05:01] "POST /api/device/switch HTTP/1.1" 500 -
2020-02-10 22:00:47.519 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:01:14.026 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:02:29.241 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:08:07.020 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:09:00.151 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:09:41.893 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:10:44.081 DEBUG main - <module>: Iniciando Servicio
2020-02-10 22:11:29.914 DEBUG main - <module>: Iniciando Servicio
2020-02-12 02:52:31.775 DEBUG main - <module>: Iniciando Servicio
2020-02-12 02:52:31.872 DEBUG main - main: Conectando al broker
2020-02-12 02:52:31.949 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:06:11.187 ERROR app - log_exception: Exception on /test [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-12 03:06:11.209 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:06:11] "[35m[1mPOST /test HTTP/1.1[0m" 500 -
2020-02-12 03:07:00.556 ERROR app - log_exception: Exception on /test [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-12 03:07:00.568 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:07:00] "[35m[1mPOST /test HTTP/1.1[0m" 500 -
2020-02-12 03:10:58.339 ERROR app - log_exception: Exception on /test [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-12 03:10:58.347 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:10:58] "[35m[1mPOST /test HTTP/1.1[0m" 500 -
2020-02-12 03:14:35.113 ERROR app - log_exception: Exception on /test [POST]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-02-12 03:14:35.118 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:14:35] "[35m[1mPOST /test HTTP/1.1[0m" 500 -
2020-02-12 03:16:07.567 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:16:07.607 DEBUG main - main: Conectando al broker
2020-02-12 03:16:07.664 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:16:18.055 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:16:18] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:22:42.341 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:22:42.384 DEBUG main - main: Conectando al broker
2020-02-12 03:22:42.454 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:24:28.978 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:24:28] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:24:47.315 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:24:47] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:26:43.813 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:26:43.902 DEBUG main - main: Conectando al broker
2020-02-12 03:26:43.970 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:27:29.987 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:27:29] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:28:12.239 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:28:12.278 DEBUG main - main: Conectando al broker
2020-02-12 03:28:12.378 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:30:49.933 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:30:49] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:33:52.124 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:33:52.172 DEBUG main - main: Conectando al broker
2020-02-12 03:33:52.229 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:33:57.018 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:33:57] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:37:33.137 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:37:33.206 DEBUG main - main: Conectando al broker
2020-02-12 03:37:33.447 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:37:48.470 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:37:48.489 DEBUG main - main: Conectando al broker
2020-02-12 03:37:48.546 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:37:54.077 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:37:54] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:39:33.669 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:39:33.710 DEBUG main - main: Conectando al broker
2020-02-12 03:39:33.769 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:39:39.360 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:39:39] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:40:39.348 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:40:39.381 DEBUG main - main: Conectando al broker
2020-02-12 03:40:39.450 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:40:46.037 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:40:46] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:42:30.016 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:42:30] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 03:44:56.159 DEBUG main - <module>: Iniciando Servicio
2020-02-12 03:44:56.223 DEBUG main - main: Conectando al broker
2020-02-12 03:44:56.277 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 03:45:00.900 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 03:45:00] "[37mPOST /test HTTP/1.1[0m" 200 -
2020-02-12 04:22:03.775 DEBUG main - <module>: Iniciando Servicio
2020-02-12 04:22:03.857 DEBUG main - main: Conectando al broker
2020-02-12 04:33:53.980 DEBUG main - <module>: Iniciando Servicio
2020-02-12 04:33:54.002 DEBUG main - main: Conectando al broker
2020-02-12 04:33:54.077 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 04:34:31.715 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 04:34:31] "[37mGET /test HTTP/1.1[0m" 200 -
2020-02-12 04:34:57.655 DEBUG main - <module>: Iniciando Servicio
2020-02-12 04:34:57.696 DEBUG main - main: Conectando al broker
2020-02-12 04:34:57.749 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 04:35:01.893 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 04:35:01] "[37mGET /test HTTP/1.1[0m" 200 -
2020-02-12 04:37:36.183 DEBUG main - <module>: Iniciando Servicio
2020-02-12 04:37:36.202 DEBUG main - main: Conectando al broker
2020-02-12 04:37:36.265 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 04:40:21.475 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 04:40:21] "[37mGET /test HTTP/1.1[0m" 200 -
2020-02-12 04:41:50.680 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 04:41:50] "[37mGET /test HTTP/1.1[0m" 200 -
2020-02-12 04:49:07.789 DEBUG main - <module>: Iniciando Servicio
2020-02-12 04:49:08.003 DEBUG main - main: Conectando al broker
2020-02-12 04:49:08.099 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 04:50:11.356 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 04:50:11] "[37mGET /test HTTP/1.1[0m" 200 -
2020-02-12 04:57:56.929 DEBUG main - <module>: Iniciando Servicio
2020-02-12 04:57:56.951 DEBUG main - main: Conectando al broker
2020-02-12 04:57:57.012 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 04:59:35.436 ERROR app - log_exception: Exception on /test [GET]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/juan/.local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/juan/Codigos/Redes de sensores/IoTBackend/main.py", line 235, in get_test
    return jsonify(jsonResp)
NameError: name 'jsonify' is not defined
2020-02-12 04:59:35.460 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 04:59:35] "[35m[1mGET /test HTTP/1.1[0m" 500 -
2020-02-12 05:00:18.248 ERROR app - log_exception: Exception on /test [GET]
Traceback (most recent call last):
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/juan/.local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/juan/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/juan/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/juan/Codigos/Redes de sensores/IoTBackend/main.py", line 235, in get_test
    return jsonify(jsonResp)
NameError: name 'jsonify' is not defined
2020-02-12 05:00:18.258 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 05:00:18] "[35m[1mGET /test HTTP/1.1[0m" 500 -
2020-02-12 05:01:18.009 DEBUG main - <module>: Iniciando Servicio
2020-02-12 05:01:18.050 DEBUG main - main: Conectando al broker
2020-02-12 05:01:18.111 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 05:01:27.918 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 05:01:27] "[37mGET /test HTTP/1.1[0m" 200 -
2020-02-12 05:08:22.029 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 05:08:22] "[37mGET /test HTTP/1.1[0m" 200 -
2020-02-12 06:23:37.910 DEBUG main - <module>: Iniciando Servicio
2020-02-12 06:23:37.943 DEBUG main - main: Conectando al broker
2020-02-12 06:23:38.004 INFO _internal - _log:  * Running on http://192.168.0.20:8080/ (Press CTRL+C to quit)
2020-02-12 06:24:26.571 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 06:24:26] "[37mGET /test HTTP/1.1[0m" 200 -
2020-02-12 06:24:29.017 INFO _internal - _log: 192.168.0.20 - - [12/Feb/2020 06:24:29] "[37mPOST /test HTTP/1.1[0m" 200 -
